resolver: lts-17.6
pvp-bounds: upper
packages:
- .
extra-deps:
- language-javascript-0.7.0.0
- github: purescript/purescript
  commit: v0.14.3
  subdirs:
    - lib/purescript-cst
    - '.'
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
  haskeline:
    # Avoids a libtinfo dynamic library dependency
    terminfo: false
  # Building on certain CentOS (maybe ghc) versions
  cryptonite:
    use_target_attributes: false