resolver: lts-18.15
pvp-bounds: upper
packages:
- .
extra-deps:
- language-javascript-0.7.0.0
- github: purescript/purescript
  commit: 28f5f63cd231844ee5963889a8b1b06ebc8c4e71
  subdirs:
    - lib/purescript-cst
    - '.'
# Fix issue with libtinfo.
# See https://github.com/purescript/purescript/issues/4253
- process-1.6.13.1
- Cabal-3.2.1.0
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
  haskeline:
    # Avoids a libtinfo dynamic library dependency
    terminfo: false
    examples: false
  # Building on certain CentOS (maybe ghc) versions
  cryptonite:
    use_target_attributes: false